# Generated by Django 4.1 on 2022-11-11 01:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('7bdd0c6c-2b31-49bf-8465-b55117ab5a24'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('todo_title', models.CharField(max_length=100)),
                ('todo_description', models.TextField(max_length=100)),
                ('is_done', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
