# Generated by Django 4.1 on 2022-11-11 04:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('193afedb-cd38-4eb3-9a02-61a9af25cd9f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
